### ISSUE TITLE
let's define our base sets of eslint rules!

### ISSUE THREAD

**Issue by FrancescoCioria** [buildo/eslint-config#1]
@gabro @giogonzo @francescogior @ascariandrea 

Hi everyone! In the last week only I fixed/updated like 4 `.eslintrc` configuration files so, as the base configuration is always the same, I created this new package where we can define our base sets.

For now we only have two files: `default.js` and `production.js`

But the point of this discussion is decide which sets we need and create a set of rule for each one (for example we could remove `production.js` if we don't need it or we could split `default.js` into `es6.js`, `react.js` )
## 
#### How to use it:

If you want to use these rules in a project (a buildo project you're contributing to or a personal project) you can simply install this package and then extend your `.eslintrc` like this:

``` js
// ALL
"extends": "eslint-config-buildo"

// SOME
"extends": [
  "eslint-config-buildo/rules/SOME_RULE",
  "eslint-config-buildo/rules/SOME_OTHER_RULE"
]
```

**Comment by gabro** [comment]
How would you handle `default` and `production`?

Develop with `default` and run tests/CI against `production`?

**Comment by gabro** [comment]
You can do just

``` js
{
  "extends": "buildo"
}
```

`eslint-config-` is implicitly assumed by eslint :coffee:

**Comment by gabro** [comment]
To add/remove custom rules per-project

``` js
{
  "extends": "buildo",
  "rules": {
    "comma-dangle": 0, // disable trailing commas
    "jsx-quotes": "prefer-single" // YAY!
  }
}
```

**Comment by giogonzo** [comment]
about having more than 1 config: I can see the benefit in allowing certain debug-related stuff only in `development` and instead reporting them when running CI (for private and public projects) with `production`...

But I fear the complications it would add, so my vote goes to sticking to a single config (disallowing `console` and the like)

**Comment by gabro** [comment]
I mostly agree with @giogonzo

**Comment by gabro** [comment]
Closing this as it's probably useless now.
