### ISSUE TITLE
Add spaced-comment and no-multi-spaces

### ISSUE THREAD

**Issue by giogonzo** [buildo/eslint-config#101]
Proposing these together since both very minor.. note that both are fixable

[spaced-comment](http://eslint.org/docs/rules/spaced-comment) and [no-multi-spaces](http://eslint.org/docs/rules/no-multi-spaces)

Our average code base does not agree but I think mostly because it was never enforced. There's no convention in the failing projects and they are inconsistent

|     | repo                              | errors | warnings |
| :-: | :-------------------------------- | :----: | :------: |
|  ✅  | buildo/aliniq                     |    0   |     0    |
|  ❌  | buildo/web-shared                 |   19   |     0    |
|  ❌  | buildo/lexdoit                    |   36   |     0    |
|  ❌  | buildo/ipercron                   |   10   |     0    |
|  ❌  | buildo/bobafett                   |    6   |     0    |
|  ❌  | contactlab/contacthub-sdk-browser |    3   |     0    |
|  ✅  | contactlab/contacthub-sdk-nodejs  |    0   |     0    |
|  ❌  | buildo/avenger                    |    2   |     0    |
|  ❌  | buildo/react-components           |    7   |     0    |
|  ❌  | buildo/rc-datepicker              |    2   |     0    |
|  ❌  | buildo/react-cookie-banner        |    2   |     0    |
|  ✅  | buildo/react-autosize-textarea    |    0   |     0    |
|  ✅  | buildo/react-input-link           |    0   |     0    |
|  ✅  | buildo/react-flexview             |    0   |     0    |
|  ✅  | buildo/react-placeholder          |    0   |     0    |
|  ❌  | buildo/local-date                 |    1   |     0    |
|  ❌  | buildo/formo                      |   12   |     0    |
|  ✅  | buildo/hophop                     |    0   |     0    |
|  ✅  | buildo/nemobot                    |    0   |     0    |
|  ❌  | buildo/prisma                     |    3   |     0    |
|  ✅  | buildo/pledge                     |    0   |     0    |

**Comment by gabro** [comment]
Mm, seeing this I kind want to add a 'linto --fix' that automatically opens the PRs...

**Comment by giogonzo** [comment]
that would be 💅 ❤️

**Comment by gabro** [comment]
oh well, https://github.com/buildo/formo/pull/35

**Comment by giogonzo** [comment]
closed by #104
