### ISSUE TITLE
pin eslint-plugin-react to <6.10.1

### ISSUE THREAD

**Issue by veej** [buildo/eslint-config#108]
## requirements
Due to https://github.com/yannickcr/eslint-plugin-react/issues/1117, `eslint-plugin-react` is breaking our builds.

## specs
Pin `eslint-plugin-react` to version <6.10.1

## misc
{optional: other useful info}

**Comment by yannickcr** [comment]
`v6.10.3` is now published and should fix the issue. Sorry for the inconvenience.

**Comment by gabro** [comment]
@yannickcr thank you for the quick fix and for letting us know! 👍  Keep up with the great work!
