### ISSUE TITLE
Disallow Use of `undefined` Variable (no-undefined)

### ISSUE THREAD

**Issue by FrancescoCioria** [buildo/eslint-config#111]
Disallow Use of `undefined` Variable (no-undefined)

eslint rule: http://eslint.org/docs/rules/no-undefined

**Comment by gabro** [comment]
linto report?

**Comment by FrancescoCioria** [comment]
mmm, that rule forbids other things we use and like -> ex: `x = y ? t.ciao : undefined`

what I really wanted to forbid was `x === undefined` as at buildo we all agreed to use `typeof x !== 'undefined'`...
soo, I'll close this issue for now
