### ISSUE TITLE
Enfore space before '/>' in self-closing tags

### ISSUE THREAD

**Issue by ecamellini** [buildo/eslint-config#113]
## requirements
In case of self-closing tags (e.g., `<MyComponent />`) a space should always be present before the closing `/>`.

Example:
The following should be considered an error: `<MyComponent/>`

## specs
{optional: describe technical specs to implement this feature, if not obvious}

## misc
{optional: other useful info}

**Comment by gabro** [comment]
I agree with picking a rule for this, is there an existing rule that does it?

**Comment by veej** [comment]
https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-space-before-closing.md

**Comment by gabro** [comment]
Some volunteer to run a linto report?

**Comment by gabro** [comment]
Detailed instructions here: https://github.com/buildo/eslint-config#proposing-a-new-rule

**Comment by ecamellini** [comment]
@gabro there is a rule, I already sent a PR but didn't run linto report. I can try to do it

**Comment by gabro** [comment]
Yes, please. If you have problems, let me know so that we can update the guide :)

**Comment by ecamellini** [comment]
@gabro I don't have the rights to access some of the repos. These are the results so far:
![image](https://cloud.githubusercontent.com/assets/6418684/25857810/6f2c06c0-34da-11e7-9c46-b256a92cecd1.png)

**Comment by veej** [comment]
|     | repo                              | errors | warnings |
| :-: | :-------------------------------- | :----: | :------: |
|  ❌  | buildo/aliniq                     |   77   |     0    |
|  ❌  | buildo/web-shared                 |   34   |     0    |
|  ❌  | buildo/lexdoit                    |   17   |     0    |
|  ❌  | buildo/ipercron                   |    6   |     0    |
|  ✅  | buildo/bobafett                   |    0   |     0    |
|  ✅  | contactlab/contacthub-sdk-browser |    0   |     0    |
|  ✅  | contactlab/contacthub-sdk-nodejs  |    0   |     0    |
|  ✅  | buildo/avenger                    |    0   |     0    |
|  ❌  | buildo/react-components           |    2   |     0    |
|  ✅  | buildo/rc-datepicker              |    0   |     0    |
|  ✅  | buildo/react-cookie-banner        |    0   |     0    |
|  ✅  | buildo/react-autosize-textarea    |    0   |     0    |
|  ✅  | buildo/react-input-link           |    0   |     0    |
|  ✅  | buildo/react-flexview             |    0   |     0    |
|  ❌  | buildo/react-placeholder          |    2   |     0    |
|  ✅  | buildo/local-date                 |    0   |     0    |
|  ❌  | buildo/formo                      |    3   |     0    |
|  ✅  | buildo/hophop                     |    0   |     0    |
|  ✅  | buildo/nemobot                    |    0   |     0    |
|  ✅  | buildo/prisma                     |    0   |     0    |
|  ✅  | buildo/pledge                     |    0   |     0    |

**Comment by gabro** [comment]
Thanks! It's also fixable, so maybe linto can fix all projects automagically 😇

**Comment by giogonzo** [comment]
Can someone remove web-shared? It's ☠

**Comment by gabro** [comment]
Oh, dead? I was fixing it :D

**Comment by gabro** [comment]
aaand it's gone (from linto-config)

**Comment by gabro** [comment]
If somebody wants to have the pleasure:

```sh
yarn global add linto
linto run --fix -n -c linto-config.yml
```

remove `-n` to actually open the pull requests

**Comment by veej** [comment]
oh, and since we're on the subject, could you add GDSM projects please? :P

**Comment by gabro** [comment]
Done!
