### ISSUE TITLE
some established rules have disappeared!

### ISSUE THREAD

**Issue by FrancescoCioria** [buildo/eslint-config#15]
`no-unused-vars`, `comma-dangle`, `semi`, `no-trailing-spaces`, `quotes`
where have they gone? :) @gabro @giogonzo 

I think we should definitely re add them, especially `no-unused-vars` (detects useless imports too)

**Comment by FrancescoCioria** [comment]
I'm not sure if `quotes: [2, "single"]` will complain about jsx quotes too...

**Comment by giogonzo** [comment]
I removed what is already part of eslint:recommended but probably I missed something.. 

About quotes no, they shouldn't overlap

**Comment by ascariandrea** [comment]
I think also `semi` (for semicolons) has been deactivated..

**Comment by FrancescoCioria** [comment]
@ascariandrea yes, it's in the list above :stuck_out_tongue_closed_eyes:

**Comment by ascariandrea** [comment]
I'm blind :see_no_evil:

**Comment by gabro** [comment]
`quotes` does not consider jsx-quotes
