### ISSUE TITLE
why are we repeating some rules from eslint:recommended?

### ISSUE THREAD

**Issue by giogonzo** [buildo/eslint-config#19]
Just something we need to check / understand:

as pointed out here #15 , some rules weren't being checked without explicitly repeating them even though they are part of `eslint:recommended` (I think just `no-unused-vars`, `comma-dangle`, see http://eslint.org/docs/rules/)

**Comment by gabro** [comment]
Is this still actual?

**Comment by FrancescoCioria** [comment]
I actually think we should do the opposite: we're relying on `eslint:recommend` for rules we find useful. Unfortunately they're not simply adding rules to the recommended group, sometimes they're removing some from it or editing them (ex: https://github.com/eslint/eslint/commit/79ebbc962fedeadfe8e69d8a43ed1f5bf440d0cf)
I think it would be safer and more stable to repeat the rules we're 100% sure we want wether or not they're recommended (we can still keep `eslint:recommended` as an integration)

**Comment by gabro** [comment]
I agree. If the set of rules is not stable and not under our control, let's just copy them over and be done with it.

**Comment by gabro** [comment]
On a second thought, I have a different proposal.

Changes to recommended rules are clearly marked as **breaking** in eslint releases.

How about we fix to a specific version of eslint (e.g. 2.4) and when we manually update it, we check for breaking changes (as we should do anyway)?

**Comment by giogonzo** [comment]
always in favor of pinning versions :+1:

**Comment by gabro** [comment]
I took a look at this, and it looks like eslint is not introducing breaking changes on minor releases, so I think our peer dependency on `^2.4.0` is already good enough.

Thoughts @buildo/frontend?

**Comment by FrancescoCioria** [comment]
> How about we fix to a specific version of `eslint` (e.g. 2.4) and when we manually update it, we check for breaking changes (as we should do anyway)?

I agree... but let's remember to check! :)

**Comment by gabro** [comment]
Ok. Nothing do do here. :)
