### ISSUE TITLE
jsx-quotes: 'prefer-single'

### ISSUE THREAD

**Issue by gabro** [buildo/eslint-config#2]
Currently we use `jsx-quotes` with `prefer-double` which enforces double quotes on JSX strings, but at the same time we use single quotes for strings.

Many others (see airbnb) do the same, and this is the usually the motivation:

> Why? JSX attributes can't contain escaped quotes, so double quotes make conjunctions like "don't" easier to type. Regular HTML attributes also typically use double quotes instead of single, so JSX attributes mirror this convention.

However, in our case:
- you typically need apostrophes while writing English text in attributes. We don't usually do this (strings are in a separate json file) and in the rare circumstances you can always fallback on double quotes (eslint won't complain if you use a single quote inside the string)
- about consistency with HTML attributes, I personally couldn't care less, do you?

I vote to keep consistency between strings and use single quotes for JSX too.

Thoughts?

/cc @buildo/frontend-opensource

**Comment by francescogior** [comment]
+1 for single quotes!
- it's lighter (more beautiful to see)
- JSX in the end is (transpiled) to JS

**Comment by giogonzo** [comment]
no explicit preference here, `prefer-double` is there in our projects (sometimes) just because it is "the standard"

anyway it is not `eslint --fix`able yet as a rule. ~~We could consider to make it fixable in `eslint` which seems a "good first bug" (easy)~~ There's this: https://github.com/eslint/eslint/pull/4374

**Comment by gabro** [comment]
Autofix support has been merged (https://github.com/eslint/eslint/pull/4932).
Waiting for the next eslint release.

**Comment by gabro** [comment]
Merged on eslint, fix now works.
