### ISSUE TITLE
add wrap-iife: [2, "inside"]

### ISSUE THREAD

**Issue by giogonzo** [buildo/eslint-config#34]
http://eslint.org/docs/rules/wrap-iife.html

for readability, I think

``` js
(a => {
 // ...
})();
```

is better than both 

``` js
a => {
// ...
}();
```

and

``` js
(a => {
// ...
}());
```

e.g. see https://github.omnilab.our.buildo.io/buildo/labonline/pull/1510/files#diff-5987c54300ae1129b26846f0f758a1c6R90

**Comment by gabro** [comment]
+1!
