### ISSUE TITLE
consider adding no-extra-parens

### ISSUE THREAD

**Issue by giogonzo** [buildo/eslint-config#39]
http://eslint.org/docs/2.0.0/rules/no-extra-parens

**Comment by gabro** [comment]
@buildo/frontend is there any agreement on this?

I vote for adding it.

**Comment by ascariandrea** [comment]
+1

**Comment by giogonzo** [comment]
FYI ended up disabling this in LOL, it doesn't have a granular configuration and it complains for stuff like:

``` js
  headerTitleTemplate = () => (
    <FlexView vAlignContent='center'>
      ...
    </FlexView>
  );
```

**Comment by FrancescoCioria** [comment]
same problems on `b-r-c`, too many false positives. It complains about this too:

``` js
if (hours === 0 || (hours > 12 && hours % 12 === 0)) { ... }
```

I think those parentheses aren't useless as it's much easier to read the expression with them

**Comment by gabro** [comment]
Ok, bad call. Let's revert it
