### ISSUE TITLE
react/jsx-equals-spacing doesn't work

### ISSUE THREAD

**Issue by ascariandrea** [buildo/eslint-config#47]
Atom complains about rule definition not found and `eslint` doesn't complain at all about `react/jsx-equals-spacing`.

Seems related to `eslint-react-plugin` version: [https://github.com/yannickcr/eslint-plugin-react/issues/21](https://github.com/yannickcr/eslint-plugin-react/issues/21)

**Comment by gabro** [comment]
Is this still actual, @ascariandrea?

**Comment by ascariandrea** [comment]
Nope, we can close it now as it was resolved by a new `eslint-react-plugin` version.

**Comment by gabro** [comment]
Perfect, thanks!
