### ISSUE TITLE
Disable global find

### ISSUE THREAD

**Issue by ascariandrea** [buildo/eslint-config#56]
## requirements
- eslint doesn't mark `find` as undefined variables (cause it's a `js` native function)
## specs
- turn off the global `find` var
## misc
- my experience is I only use the `lodash` `find` method and sometimes I forget to import in the current file. No lint errors, but code doesn't work and I lose time debugging :/

**Comment by giogonzo** [comment]
So yes, `find` is a `browser` env non-assignable global: https://github.com/sindresorhus/globals/blob/master/globals.json#L27
Looking at this doc http://eslint.org/docs/user-guide/configuring#specifying-globals, it's not clear how to "unset/disable" it (remove just `find` as global)

Any pointers?

**Comment by giogonzo** [comment]
found this: http://eslint.org/docs/rules/no-restricted-globals
