### ISSUE TITLE
consider more plugins to include

### ISSUE THREAD

**Issue by giogonzo** [buildo/eslint-config#6]
I have these on my list:
- https://github.com/jussi-kalliokoski/eslint-plugin-no-implicit-side-effects (forget the `void` stuff, we can just disable inline when needed, and it should be in some very special cases) (also there's a good list of other rules we could add at the end of the readme)
- https://github.com/benmosher/eslint-plugin-import

what do you think?

**Comment by FrancescoCioria** [comment]
Does `eslint-plugin-import` also prevent osx case-insensitive issues?
Anyway, they both look useful! (The first one might cause a big refactor though. I suggest we try it first)

**Comment by giogonzo** [comment]
> Does eslint-plugin-import also prevent osx case-insensitive issues?

Not sure, but I fear that is at a much lower level: "case-insesitivity-broken" imports will look good to `eslint-plugin-import` too on OSX

**Comment by gabro** [comment]
+1 for both

**Comment by giogonzo** [comment]
`eslint-plugin-no-...` requires node v4, so paused for now

about `eslint-plugin-import` (testing on LOL): it is slowing everything down a lot but it has proved useful: I found a few useless files that could have been removed + a few duplicate imports from `Basic` in multiple files

See more here: https://github.omnilab.our.buildo.io/buildo/labonline/pull/1417

It is also complaining for this (in b-r-c): 

```
> cat node_modules/buildo-react-components/src/flex/index.js
import FlexView from './FlexView';
import FlexCell from './FlexCell';

export default { FlexView, FlexCell };
```

Not yet sure if just a configuration issue, but anyway the exports there could be better written as:

``` js
export FlexView from './FlexView';
export FlexCell from './FlexCell';
```

**Comment by gabro** [comment]
@giogonzo want to re-evaluate these?

**Comment by giogonzo** [comment]
`eslint-plugin-import` is really helpful, but not fast enough on our average code base I think. Maybe it can be configured with excludes to help with performance

I still like both, but I honestly don't have the time to do it.. closing for now
