### ISSUE TITLE
[Rules] Add max-len rule

### ISSUE THREAD

**Issue by ascariandrea** [buildo/eslint-config#60]
## requirements

We should add the rule to lint very long lines.
The default value for code line is `80`, which could be fine (to test before) and comments are configurable.
## specs
- [eslint max-len](http://eslint.org/docs/rules/max-len)
## misc

{optional: other useful info}

c/c @buildo/frontend

**Comment by gabro** [comment]
I'm in favor, not sure 80. 100 maybe?

**Comment by giogonzo** [comment]
💯 💯 💯 
yes at least 100 IMO, but we should test on specific cases

**Comment by francescogior** [comment]
at buildo I'm the one with the smallest display and with the biggest font-size 👓 but `120` chars don't wrap!

**Comment by ascariandrea** [comment]
I'm going to try with 120 🙈

**Comment by gabro** [comment]
120 is way too much for working with split screens.

Also the GitHub mobile interface has 80 characters.

No more that 100, IMHO.
