### ISSUE TITLE
plugin idea: eslint-plugin-tcomb

### ISSUE THREAD

**Issue by gabro** [buildo/eslint-config#62]
A plugin to enforce some conventions in tcomb.

Possible rules:
#### description

types should always have a name
#### specs

check last arguments of type definitions

---
#### description

structs should be `strict` by default
#### specs

second argument of `t.struct` should be an object with `strict: true`

**Comment by gcanti** [comment]
`no-unchecked-enums`

**Description**

every check involving a string (`=== string`) should be wrapped by an enum

**Example**

``` js
// bad
if (myvar === 'myenum') {
  ...
}

// good
if (myvar === MyEnum('myenum')) {
  ...
}
```

**Comment by giogonzo** [comment]
Nice!

> `=== 'string'`

this check could be too broad, we probably have legit cases when you want to be able to === 'string'.. do we?

**Comment by gabro** [comment]
`no-unchecked-enums` I would love this, but I have the same concern

> every check involving a string (=== string)

I fear this will have counter-examples, can we think of one?

**Comment by gabro** [comment]
In the meanwhile... https://github.com/buildo/eslint-plugin-tcomb

**Comment by gcanti** [comment]
@gabro awesome, I'll add a link to `tcomb`'s README

**Comment by gabro** [comment]
other ideas: `no-any`

**Comment by gcanti** [comment]
We should open an issue (issues) on the new repo, I guess

**Comment by gabro** [comment]
Ok, closing this and let's track stuff on the repo
