### ISSUE TITLE
new rules proposal

### ISSUE THREAD

**Issue by gabro** [buildo/eslint-config#63]
Add [`no-extend-native`](http://eslint.org/docs/rules/no-extend-native) and [`no-native-reassign`](http://eslint.org/docs/rules/no-native-reassign)

/cc @buildo/frontend

**Comment by FrancescoCioria** [comment]
👍  they look very reasonable and a safe addition (I expect to have ~zero errors in our projects, right?)

**Comment by giogonzo** [comment]
yes I expect 0 errors, do you have an actual use case where this would have helped you @gabro ?

Anyway 👍 for adding

**Comment by gabro** [comment]
no use case, I just stumbled upon them today and realized we didn't include them

**Comment by gabro** [comment]
woops, [I commited directly on master](https://github.com/buildo/eslint-config/commit/c3d86afc1f5c561fe4231be9ab8b71b9dce62b30). Anyone against?

**Comment by gabro** [comment]
apparently not
