### ISSUE TITLE
want: no-magic-numbers

### ISSUE THREAD

**Issue by giogonzo** [buildo/eslint-config#64]
http://eslint.org/docs/rules/no-magic-numbers

**Comment by gabro** [comment]
+1. Any data from our code bases?

**Comment by FrancescoCioria** [comment]
#sbatti (I like the idea, but it's heavy.. ex: `style: { margin: 30 }` or `<FlexView basis={100} ...`)

**Comment by FrancescoCioria** [comment]
- LOL: 330
- brc
  - /src: 116
  - /test: 47

**Comment by giogonzo** [comment]
I guess majority is in component inline style? Anyway it doesn't look much configurable :(

**Comment by giogonzo** [comment]
(btw /test shouldn't probably be considered)

**Comment by giogonzo** [comment]
(obviously lost your first comment edit..)

**Comment by gabro** [comment]
looks not feasible for us to adopt. Closing until it's more configurable
