### ISSUE TITLE
want: dot-location

### ISSUE THREAD

**Issue by dhinus** [buildo/eslint-config#65]
http://eslint.org/docs/rules/dot-location

**Comment by gabro** [comment]
As discussed on Slack, the general consensus seems to be "property", e.g.

```
foo
  .bar
  .baz
```

as opposed to "object":

```
foo.
  bar.
  baz
```

thoughts? @buildo/frontend

**Comment by gabro** [comment]
0 style issues found on LOL with `property` 🎉

**Comment by FrancescoCioria** [comment]
I already write my code like this so 👍
