### ISSUE TITLE
comma dangle

### ISSUE THREAD

**Issue by gabro** [buildo/eslint-config#69]
I'm really tired of seeing diffs like this

``` diff
const props = {
-  allowBlah: true
+  allowBlah: true,
+  isBaz: false
};
```

😠 

or

``` diff
const props = {
- allowBlah: true,
- isBaz: false
+ allowBlah: true
};
```

😧  

I'm proposing to change comma-dangle from `never` to `always-multiline`, so that we can have nice diffs:

``` diff
const props = {
  allowBlah: true,
+ isBaz: false,
};
```

🎉 

or

``` diff
const props = {
  allowBlah: true,
- isBaz: false,
};
```

💯 

I'm not a big fan of it from a purely _aesthetic_ point of view, but the advantages are pretty huge when it comes to diffs.

It also makes much easier and less error prone to manipulate objects and arrays, as you don't have to remember to add/remove commas to the last lines.

/cc @buildo/frontend

**Comment by gabro** [comment]
In case you're wondering, I'm proposing `always-multiline` and `always` because we don't want this

``` javascript
const x = { allowBlah: true, isBaz: false, }
```

Ugh... 😨 

With `always-multine` the comma is required only in multiline objects/arrays, and forbidden in in-line ones. 👍

**Comment by FrancescoCioria** [comment]
😢  (very bad-looking)

**Comment by gabro** [comment]
I know, but what about the other concerns? I think the diff part is huge (and it's also easier when writing code)

**Comment by gabro** [comment]
@buildo/frontend let's take a decision on this (vote under the original post)

**Comment by gabro** [comment]
Apparently we voted against this. Enjoy your messy diffs! 😭
