### ISSUE TITLE
add more rules to default config

### ISSUE THREAD

**Issue by giogonzo** [buildo/eslint-config#7]
some experiments in: https://github.omnilab.our.buildo.io/buildo/labonline/blob/web-1416-test_new_eslint_plugins/web/.eslintrc

that `.eslintrc` should contain exactly the proposed diff wrt current `buildo/default`

(note that `no-this-before-super` is already here but disabled (for no reason?))

Some of the rules that I added are a bit opinionated, e.g. `no-plusplus`.. but it made me discover this beauty: https://github.omnilab.our.buildo.io/buildo/labonline/blob/web-1416-test_new_eslint_plugins/web/src/app/components/Basic/Tabs/Tabs.js#L43-L56

Let's discuss these and/or other possible additions in this issue

**Comment by francescogior** [comment]
:innocent:

**Comment by giogonzo** [comment]
@gabro @FrancescoCioria @francescogior added more rules in linked PR. Please comment now or forever hold your peace
