### ISSUE TITLE
curly

### ISSUE THREAD

**Issue by giogonzo** [buildo/eslint-config#72]
http://eslint.org/docs/rules/curly

set on `"all"`, basically:

**ok**

``` js
if (something) {
  somethingElse();
}
```

**not ok**

``` js
if (something) somethingElse();
```

Given that there are only 2 errors in the current LOL codebase (and both by @dhinus :P) it should be a relatively shared rule among buildojsers

@buildo/frontend thoughts?

**Comment by dhinus** [comment]
Personally I like one-line if statements. 😛 
I vote for the [multi-line](http://eslint.org/docs/rules/curly#multi-line) option!

Ok:

``` js
if (foo) foo++; else doSomething();
```

Not ok:

``` js
if (foo) foo(
  bar,
  baz);
```

**Comment by gabro** [comment]
My vote goes to `all`. Less surprising to parse.

**Comment by ascariandrea** [comment]
I'm for `all`!
@dhinus you can always write

``` js
something && doSomething();
```

**Comment by dhinus** [comment]
Ok, I can live with that :)

**Comment by gabro** [comment]
@buildo/frontend let's take a decision on this, vote as a reaction to the original post!

**Comment by gabro** [comment]
Done in https://github.com/buildo/eslint-config/commit/6bb52e0c4c25a0b5ff9b4cc4f5b0ecf9e23d772b
