### ISSUE TITLE
max-len should ignore URLs, strings and imports

### ISSUE THREAD

**Issue by FrancescoCioria** [buildo/eslint-config#74]
## requirements

IMO `max-len` (to be finally more useful than annoying) should ignore URLs, strings and imports.
http://eslint.org/docs/rules/max-len#ignoreurls

@buildo/frontend 
## specs
- ignore strings, URLs and templateLiteral
- add regexp to ignore imports
## misc

{optional: other useful info}

**Comment by gabro** [comment]
sounds good to me

**Comment by gabro** [comment]
not sure about imports, those can be easily split into multiple lines, if you're destructuring.

**Comment by FrancescoCioria** [comment]
Yes, we should probably remove the ugly regex for the imports

**Comment by FrancescoCioria** [comment]
We reverted the PR due to a breaking change in "max-len" syntax that broke projects with `eslint@2`.

We should first upgrade every project that depends on this rules to `eslint@3` and than re-merge the PR
