### ISSUE TITLE
upgrade eslint-plugin-react

### ISSUE THREAD

**Issue by FrancescoCioria** [buildo/eslint-config#82]
## requirements
let's upgrade `eslint-plugin-react` to v6.x

## specs
{optional: describe technical specs to implement this feature, if not obvious}

## misc
{optional: other useful info}

**Comment by ascariandrea** [comment]
I want the [sort-comp](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/sort-comp.md) :)
